### PR TITLE
chore(Typescript): add type for the second argument of the appropriate getter props

### PR DESCRIPTION
**Pull request by k88manish**
**What**:
Typings were missing for `getInputProps` and `getMenuProps`  while using `useCombobox` hook with Typescript

**Why**:
To prevent compile time error from Typescript compiler

**How**:

**Checklist**:

- [ ] Documentation 
- [ ] Tests 
- [x] TypeScript Types
- [ ] Flow Types 
- [ ] Ready to be merged

### CODE REVIEW

**Comment by silviuaavram** [comment]
Hi! I don't believe these changes are correct. Based on what usage are you adding them, can you provide an example?

**Comment by silviuaavram** [comment]
Actually if you are thinking about the parameter that takes `suppressRefError` you are probably right. Let me review this.

**Comment by k88manish** [comment]
> Actually if you are thinking about the parameter that takes `suppressRefError` you are probably right. Let me review this.

Yes, I was trying to use `supressRefError` options but as typing doesn't support second argument it gave me error 
image

**Comment by sluukkonen** [comment]
I think the same change also should be done for `useSelect` props.

**Comment by silviuaavram** [comment]
Yeah. Here is the PR which added the checks for the getter props in the hooks https://github.com/downshift-js/downshift/pull/1053/files . Our type updates should cover the changes there

**Comment by k88manish** [comment]
Should we add typing for `useSelect` as well?

**Comment by silviuaavram** [comment]
useCombobox (getComboboxProps, getInputProps, getMenuProps), useSelect (getMenuProps, getToggleButtonProps) and useMultipleSelection (getDropdownProps).

**Comment by k88manish** [comment]
> useCombobox (getComboboxProps, getInputProps, getMenuProps), useSelect (getMenuProps, getToggleButtonProps) and useMultipleSelection (getDropdownProps).

Updated these as well

**Comment by k88manish** [comment]
@silviuaavram Did you get a chance to review it?

**Comment by k88manish** [comment]
> Done, you added two incorrect ones (for Downshift) and missed one (for useSelect). Overall looks good, please integrate comments and we should be ready to merge.

Updated as per comments

**Comment by silviuaavram** [comment]
@all-contributors please add @k88manish for code

**Comment by hd4ng** [comment]
Hi @silviuaavram, will the next release that include this pr available soon?

**Comment by silviuaavram** [comment]
Yes, I will do a manual release today. Unfortunately it did not get released automatically because I typed chore instead of fix in the PR name. My bad.

**Comment by silviuaavram** [comment]
Due to the current npm outage the publish failed. We will give it another go later today or tomorrow.

**Pull request merged**
