### PR TITLE
chore: Add type for GetLabelPropsReturnValue, to reduce usage of :any

### PR DESCRIPTION
**Pull request by greydnls**
**What**: Adding an interface to replace the `any` typing used for `getLabelProps` prop-getter return value. 

**Why**: 
To provide a more robust type system for downshift usage in typescript. 

**How**:
I essentially reused the interface from the flow type definition.                                             

**Checklist**:

- [ ] ~~Documentation~~ N/A
- [ ] ~~Tests~~ N/A
- [x] TypeScript~~ Types 
- [ ] ~~Flow Types~~ N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by karlhorky** [comment]
@silviuaavram what do you think about this change?

I guess ideally, it would also take into account the props object value parameter passed in, eg:

```ts
getLabelProps: <Options extends GetLabelPropsOptions>(options?: Options) => Options & GetLabelPropsReturnValue
```

**Comment by silviuaavram** [comment]
I agree with it, I am keeping this PR open until v7, since type changes are breaking changes. I am planning to re-write the hooks using typescript so will probably include this change as well. Thanks!

**Comment by silviuaavram** [comment]
Actually, the way our API works, the getter props may return anything, since they return also the extra arguments you pass to them. getLabelProps({foo: 'bar'}) will return {foo: 'bar', htmlFor: 'something', id: 'something else'}.

This may require generics. `getLabelProps: <T = void>(options?: GetLabelPropsOptions & T) => T & {htmlFor: string, id: string}`.

It can be a great improvement to get rid of our `any` returns.

**Comment by silviuaavram** [comment]
@karlhorky what do you think about
```ts
export interface GetLabelPropsReturnValue {
  htmlFor: string
  id: string
}
...
  getLabelProps: <Options>(
    options?: Options & GetLabelPropsOptions,
  ) => GetLabelPropsReturnValue & Options
```

**Comment by karlhorky** [comment]
Nice, it's been a while since I've looked at this, so not sure off the top of my head, but seems like it could work?

**Pull request closed without merging**
