### PR TITLE
fix(useCombobox): allow to submit form on pressing Enter

### PR DESCRIPTION
**Pull request by TrySound**
**What**:

Ref https://github.com/downshift-js/downshift/issues/1019

**How**:

Allow to submit form on pressing Enter when menu is closed or
no item is selected.

**Checklist**:

- [ ] Documentation
- [x] Tests
- [ ] TypeScript Types
- [ ] Flow Types
- [x] Ready to be merged

### CODE REVIEW

**Comment by TrySound** [comment]
I reproduced tests from Downshift component. What does coverage want from me?

**Comment by silviuaavram** [comment]
Looks awesome! Thank you for these changes!

**Comment by TrySound** [comment]
@silviuaavram Is this good to merge?

**Comment by silviuaavram** [comment]
Merged, thanks for fixing the conflict!

**Pull request merged**
