### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced!

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /other/public/logo/downshift.svg | 2.40kb | 2.39kb | 0.33% |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by MichaelDeBoey** [comment]
Ping @silviuavram

**Comment by silviuavram** [comment]
we don't have images in this repo. why is this relevant?

**Comment by MichaelDeBoey** [comment]
@silviuavram It also optimizes `svg`s

**Pull request closed without merging**
