### PR TITLE
fix(isOrContainsNode): check if child is instance of Node

### PR DESCRIPTION
**Pull request by askucherov**
Fixes [#1155](https://github.com/downshift-js/downshift/issues/1155)

### CODE REVIEW

**Comment by silviuaavram** [comment]
Hi! Thank you for fixing this. Will fix the CI and will merge this one afterwards!

**Comment by silviuaavram** [comment]
@askucherov can you rebase this PR? It should pass now.

**Comment by askucherov** [comment]
@silviuaavram something went wrong with the build

**Comment by silviuaavram** [comment]
Yeah let's wait for https://github.com/downshift-js/downshift/pull/1201 and try again. Sorry :(

**Comment by silviuaavram** [comment]
try now, I merged the build fix

**Comment by askucherov** [comment]
It is done! Thanks a lot for your job 👍

**Pull request merged**
