### PR TITLE
fix(highlightedIndex): do not highlight disabled items by keyboard

### PR DESCRIPTION
**Pull request by silviuavram**
**What**:

Allows disabled items to be skipped by keyboard highlight (arrow keys, home, end, character keys).

**Why**:

To have this scenario properly working.

**How**:

Refactored the utils methods that handle the index generation logic for highlighting. These methods also request `getItemNodeFromIndex` that will tell them if the item is marked as disabled or not.

This method comes from the hooks / component and is sent as parameter to the utils functions.

Test cases:

- find next non-disabled if next is disabled on arrow down.
- find prev non-disabled if prev is disabled on arrow up.
- if not circular and no non-disabled item can be highlighted, index should stay the same.
- if circular, the search for non-disabled item is resumed from first / last item.

- on home/end, if first/last are disabled, then start searching downwards/upwards for first non-disabled.

- on character key (useSelect) it will not highlight if item is disabled, it will search instead for the next item that starts with the key(s) and is not disabled.

Additional changes:
- `useSelect` has `false` default prop for `circularNavigation`, while `useCombobox` has it `true.
- unit tests in getItemProps for `<Downshift>`.
- `useCombobox` now works properly with `initialHighlightedIndex` and `defaultHighlightedIndex`.
- full testing for the `getNextWrappingIndex` and `getItemIndexByCharacterKey`

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] TypeScript Types
- [ ] Flow Types
- [ ] Ready to be merged
      

Started to work based on https://github.com/downshift-js/downshift/pull/752

Closes https://github.com/downshift-js/downshift/issues/728 https://github.com/downshift-js/downshift/issues/825

### CODE REVIEW

**Comment by weyert** [comment]
How can we progress this PR? Would it be possible to merge this PR with the logic for vanilla downshift and have the useSelect scenarios as enhancement?

**Comment by silviuavram** [comment]
@weyert we should be close with this. I only need to add tests to the hooks and finish the PR description.

**Comment by weyert** [comment]
Which tests need to be added? Looks like it already has 100% coverage?

**Comment by silviuavram** [comment]
I was not 100% confident even with that coverage so added separate tests for the index generating function. Now it's better.

**Comment by weyert** [comment]
Amazing, thanks @silviuavram :D

**Comment by weyert** [comment]
Awesome! Thank you, excited about this 😀

**Comment by silviuavram** [comment]
@all-contributors please add @jgodi for code

**Pull request merged**
