### PR TITLE
docs(useSelect): add button type "button" to useSelect docs

### PR DESCRIPTION
**Pull request by fcrezza**
**What**:
add button type "button" to avoid automatic form submission when using the hook on the form element

**Checklist**:

- [x] Documentation
- [ ] Tests
- [ ] TypeScript Types
- [ ] Flow Types
- [x] Ready to be merged

### CODE REVIEW

**Comment by silviuaavram** [comment]
@fcrezza can we change the PR to only include the Readme? The mdx with examples moved to downshift-docs.

**Comment by fcrezza** [comment]
@silviuaavram done

**Comment by silviuaavram** [comment]
Awesome, thank you! @all-contributors please add @fcrezza for doc, example

**Pull request merged**
