### PR TITLE
fix(useSelect): dispatch closure issue on search by key

### LINKED ISSUE #922: [useSelect]: Controlled Select reverts state on keypress
- `downshift` version: 4.0.8
- `node` version: 12.13.0
- `npm` (or `yarn`) version: 1.21.1

**What you did**:

Created a controlled Select based on `useSelect`.

**Reproduction repository**:

https://codesandbox.io/s/laughing-wu-r1wuq

**Problem description**:

After focusing the select, pressing a key (ie. "b") the state changes to "banana" but then immediately reverts to "apple"

Broke out this from #920 

/cc @mufasa71

### PR DESCRIPTION
**Pull request by mufasa71**
**What**:

dispatch should be passed as argument, otherwise closure issues happens

**Why**:

pass dispatch as argument

**How**:

changed useEffect

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] TypeScript Types
- [ ] Flow Types
- [x] Ready to be merged
      

Fixes #922

### CODE REVIEW

**Comment by silviuavram** [comment]
Maybe describe this in a little more detail please? :)

**Comment by mufasa71** [comment]
@silviuavram So in short dispatch is getting memorized in this particular place, because debounce itself is memorizing dispatch that was introduced initially. When you dispatch it inside debounce it always pass very first state. That is why reset keysAsParam is always called with staled state.

**Comment by silviuavram** [comment]
Thank you for detailing this out. Will merge the changes to fix this issue (y)

**Comment by silviuavram** [comment]
Can you re-run build and push the changed size snapshot?

**Comment by mufasa71** [comment]
@silviuavram done

**Pull request merged**
