### PR TITLE
feat(preact): add support for Preact X

### LINKED ISSUE #700: Preact 10 support
- `downshift` version: v3.2.7
- `node` version: v10.11.0
- `npm` (or `yarn`) version: npm 6.4.1

**Problem description**:

Downshift does not work with Preact 10 (currently still alpha, 10.0.0-alpha.4 at the time that I create this issue), are there already any plans to support the new Preact version?

### PR DESCRIPTION
**Pull request by francoischalifour**
## Summary

Downshift used to support Preact but its support was broken since Downshift 3.3.0 because:

- Hooks are used
- `@reach/auto-id` dependency was introduced (dependent on React)

This PR makes Downshift compatible with both Preact and Preact X. Preact X is a new Preact version with closer internals to React.

### Change Preact internals

The `VNode` shape changed:

- `attributes` -> `props`
- `nodeName` -> `type`
- `children` -> `props.children`

[Read more →](https://preactjs.com/guide/v10/upgrade-guide/#notes-for-library-authors)

### Remove top-level React imports

Preact doesn't support top-level React imports anymore to allow better tree-shaking.

```diff
- import React from 'react'
+ import {useEffect} from 'react'

- // React.useEffect()
+ // useEffect()
```

### Remove `@reach/auto-id` dependency

This util function relies on React, which breaks the Preact build. I inlined the function since it was small and Downshift's build take care of using Preact as required.

### Replace `preact-render-to-string` with `@testing-library/preact`

Preact X can be tested like React with the Preact Testing Library, it unifies the tooling.

## Preview

You can find Downshift working with Preact X in [this CodeSandbox](https://codesandbox.io/s/downshift-with-preact-x-07fd7).

## Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      
- [x] Added myself to contributors table
      

## Related

- Closes #700

### CODE REVIEW

**Comment by silviuavram** [comment]
awesome, love to see PRs just ready for merge!

**Comment by francoischalifour** [comment]
I updated this branch against `master` so that it's easier to merge.

I'd love to officially use this version for a project I'm working on. Do you have any ETA on when this could be released @silviuavram?

**Comment by silviuavram** [comment]
Already merged, should be in 3.4.0.

Just bear in mind that soon (a few weeks hopefully) I will release `useCombobox` which should provide the same functionality as `Downshift`. I aim for parity but afterwards I plan to go ahead with the hook instead of the component.

If you can, make your implementation in such a way so that when you want to switch to the hook instead you will be able.

You can also take a look at `useSelect` to have a general idea of how I plan to develop `useCombobox`.

**Pull request merged**
